### ISSUE TITLE
Display settings sometimes lost

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo-dotnetclient#113]
See OP: https://community.xibo.org.uk/t/10-players-lost-all-settings-same-time/15838/13

**Comment by sdh485** [comment]
Is the bug completely resolved? I still often experience the same error with the latest version of R 301 and Android player.

**Comment by dasgarner** [comment]
Yes this is completely resolved and wasn't an issue on Android as far as we're aware.

If you need further help, please either ask on our [community](https://community.xibo.org.uk) or the help desk as appropriate.

Thanks
