### ISSUE TITLE
IE Doesn't Render Pages Correctly

### ISSUE THREAD

**Issue by adagioajanes** [xibosignage/xibo-dotnetclient#115]
IE has been falling out of favor for other browsers, such as Edge or Chrome. Because of this, certain web pages are not written to correctly render in IE. But, the Xibo player uses IE to render web pages, and breaks a few pages I intended to show on the system.

The web page rendering engine needs to be moved away from IE to a modern browser.

**Comment by dasgarner** [comment]
Good day!

Please see: https://blog.xibo.org.uk/xibo-for-windows-v2/
