### ISSUE TITLE
HTML Package extracted even if no new package downloaded

### ISSUE THREAD

**Issue by CA-Mukesh** [xibosignage/xibo-dotnetclient#142]
When using html package even if new package is not downloaded it get extracted/overwrite.
check below debugging snapshot

![image](https://user-images.githubusercontent.com/41999400/81265097-64b04d00-903a-11ea-9682-4cf5bc052caa.png)

**Comment by dasgarner** [comment]
Thank you for your report - it looks like the logic is the wrong way around! The `lastModified` date of the package is less than the date in the marker file, so we shouldn't update.

I will log this up for the next release.

Thanks
