### ISSUE TITLE
Xibo 2.253.6 does not install VCRedist if needed

### ISSUE THREAD

**Issue by corrionc** [xibosignage/xibo-dotnetclient#145]
If Xibo Player is upgraded  from 2r200 to 2r253.6 , the Visual C++  Redistributables are not installed.  The player will crash and leave a log.xml_ that looks like
 `<trace date="2020-05-13 15:29:30" category="Error"><logdate>2020-05-13 15:29:30</logdate><thread></thread><method>Main</method><message>Unhandled Exception: Could not load file or assembly &apos;CefSharp.Core.dll&apos; or one of its dependencies. The specified module could not be found.</message>
</trace>
`

Manually installing the redist package fixes the issue.

**Comment by dasgarner** [comment]
That is odd - the installer is set to require the redist package as a pre-condition. Did the Player have access to the internet when it was being installed? I wonder if it tried to install the redist and failed?

**Comment by corrionc** [comment]
It was connected to the internet, but it looks like it'll only install the redistributable if installing in interactive mode.

Ie,
msiexec.exe /i xibo-client-v2-R253.6-win32-x86.msi  /qn Won't install the redist
msiexec.exe /i xibo-client-v2-R253.6-win32-x86.msi        Will install the redist

We're distributing the MSI via ConfigMgr, so we install silently.  Is it permissible to silently install the VC Redist when you're installing silently?

**Comment by dasgarner** [comment]
Thanks for the clarification - i'll research it.

**Comment by dasgarner** [comment]
This should work from R254 onward.
