### ISSUE TITLE
R202 Watchdog json error

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo-dotnetclient#150]
`Watchdog error: System.ArgumentException: Invalid JSON primitive: : "300" } }. at System.Web.Script.Serialization.JavaScriptObjectDeserializer.BasicDeserialize(String input, Int32 depthLimit, JavaScriptSerializer serializer) at System.Web.Script.Serialization.JavaScriptSerializer.Deserialize(JavaScriptSerializer serializer, String input, Type`

Watchdog pops up above error about invalid json in the status.json file. Same/similar issue as was fixed in R25x branch.

**Comment by dasgarner** [comment]
Solved in 250+ via:
#127
#143
