### ISSUE TITLE
R254: Incorrect Resolution information is being returned

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo-dotnetclient#151]
Player version: R254

Issue: Create a Layout that with a 4K UHD resolution. Add to the Layout content that is also 4K resolution and schedule to the Display. If you then check the Resolution column on the Displays page in CMS, the resolution appears to be incorrect.

Note: This has been tested with 4K videos and images.

**Comment by dasgarner** [comment]
This is confirmed to be related to Scale/Zoom in windows display settings - using 100% makes this work correctly.
