### ISSUE TITLE
Desktop App Web Viewer remains running between restarts/crashes

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo-dotnetclient#152]
Player Version: R254

Issue: Schedule a Layout that contains an Embed Widget using the Edge browser. If you open Task manager while the Embed is running, you will see a Process named Desktop App Web Viewer. Close the Player and this Process remains running. When the Watchdog restarts the Player, a new Process is created. This continues each time the Player is restarted.

Note: This behaviour has also been seen when using the HLS Widget.

**Comment by dasgarner** [comment]
As mentioned [here](https://github.com/windows-toolkit/Microsoft.Toolkit.Win32/issues/146) there are actually 3 processes that remain after a crash:

 - `Win32WebViewHost.exe`
 - `WWAHost.exe`
 - `RuntimeBroker.exe`

For me, they leak on Clean exit (ALT+F4) as well as on a crash/end process.

**Comment by dasgarner** [comment]
Handled in the watchdog.
