### ISSUE TITLE
Xibo screen saver not working

### ISSUE THREAD

**Issue by thanhhn253** [xibosignage/xibo-dotnetclient#173]
Steps to Reproduce:
   - Install new windows 10 pro (2004 version build 19041.450)
   - Install Xibo client for windows ([link](https://xibo.org.uk/api/downloads/windows))
   - Install Xibo.scr in the Xibo folder
   - Press the Settings button in Screen Saver Settings window and change the information and click Connect
   - Authorise the display in the CMS
   - Click the Preview button in Screen Saver Settings window
   - Black window open then close
   - Wait 1 hour, login and click the Preview button again
   - Black window open then close
   - Restart the computer
   - click the Preview button again
   - Black window open then close
   - Wait 1 hour
   - Login screen is there. No screen saver displayed

**Comment by dasgarner** [comment]
Thank you for your report - please can you reproduce this in our [community forum](https://community.xibo.org.uk), and once it is verified by the community or our support team we can mark it up as a bug?

Thanks!
