### ISSUE TITLE
2R255 Screenshot not returned if XMR message is missed

### ISSUE THREAD

**Issue by alexharrington** [xibosignage/xibo-dotnetclient#176]
If XMR message for request screenshot is missed or not delivered to the Player, it doesn't seem to then return a screenshot on its next collection. 

The tick remains in the screenshot column indefinitely.

**Comment by dasgarner** [comment]
I've tried to recreate this by disabling XMR on a Player and requesting a screenshot - which appears to deliver the screenshot successfully.

Do I need to do anything special to recreate beyond that?

**Comment by alexharrington** [comment]
Perhaps try with XMR configured to the wrong XMR server - ie so the Player thinks it is connected but it's not.

I've seen multiple times in the wild where the screenshot remains ticked and the Player is collecting.

**Comment by dasgarner** [comment]
Unfortunately I can't recreate, but I can see a theoretical way it could be missed, so I will plug that gap and see if that solves it in the wild.

**Comment by alexharrington** [comment]
OK. I'll have a go now.
