### ISSUE TITLE
R256 not working when set as screensaver

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo-dotnetclient#195]
Player version:
R256

Issue:
Set up R256 as screensaver. When due to display, the screen is instead black. An issue ahs also been reported by a community user, here is the post for reference:

https://community.xibo.org.uk/t/does-not-work-in-screensaver-mode/24323

**Comment by dasgarner** [comment]
Here is the root cause error:

```
Could not load file or assembly &apos;System.Runtime.CompilerServices.Unsafe, Version=4.0.4.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a&apos; or one of its dependencies. The located assembly&apos;s manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

This only happens when running as a screensaver.

**Comment by dasgarner** [comment]
As indicated by the OP, adding a config file for the scr solves the issue.
