### ISSUE TITLE
Interactive: Actions Implementation

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo-dotnetclient#196]
Implement Interactive Actions

- [x] Parse the XLF for Action Nodes on Layouts, Regions, the Drawer and Widgets
- [x] Listen for "touch" Actions
- [x] Add API for web hook actions in embedded server
- [x] Process the different action types
- [ ] Improvements after test

**Comment by dasgarner** [comment]
Track work in progress here: https://github.com/dasgarner/xibo-dotnetclient/tree/feature/finlay

**Comment by dasgarner** [comment]
Improvements to first pass implementation:
 - Regions can be overlapping, so `GetCurrentWidgetIdForRegion` needs to match more than one.

**Comment by DeadMerc** [comment]
Hello @dasgarner , 

I am learning how to work with action via webhooks, found these calls `trigger, duration set / expire / extend`, is it possible to achieve this tasks with current set of calls?
 - pause layout, play another video ( another layout or widget with video ), continue play from last moment
 - stop current layout, play another video ( another layout or widget with video ), start prev layout from beginning
 
 Will appreciate your answer, 
 Best Regards, Maxim

**Comment by dasgarner** [comment]
Hi Maxim,

This sort of question is better directly to the [Community](https://community.xibo.org.uk) so that it can be looked at by the team, or our great community, when they can.

The only thing we have not catered for at the moment is "continue play from last moment" - after an action has finished we go back to the beginning of the widget playing (if its a widget action) or the beginning of the layout if its a layout action.

**Comment by DeadMerc** [comment]
Got it,

Thank you for answer :)
