### ISSUE TITLE
V3 player: Cannot open status page locally.

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo-dotnetclient#214]
Player version:
300.3

Issue:
Clicking the i key on a connected keyboard does not open the status log page.

**Comment by dasgarner** [comment]
I noticed similar issues when the CTRL key modified was used - is this the case here?

**Comment by DanielBW1** [comment]
sorry Dan, I didn't notice that option. With ctrl held I can access the status page. Thanks for pointing that out.

**Comment by DanielBW1** [comment]
tested again with the ctrl key required set to false, the status window does not open unless ctrl is held.

**Comment by dasgarner** [comment]
I did make some fixes for the CTRL key: https://github.com/dasgarner/xibo-dotnetclient/commit/452e37b7cb005eec5450f3a4010939783bb8dec6

I'll get you a MSI to try that
