### ISSUE TITLE
WebView: CEF cookies not remembered after upgrade from 90.6.70 to 91.1.211

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo-dotnetclient#226]
I tested this by scheduling xibo.org.uk to be displayed and then clicked OK on the cookie message. When the layout refreshes the cookie message re-appears.

I tried the same in v3 R300.5 and the cookie message does not re-appear when the layout refreshes.

For context we did also set a RequestContext between these releases, so that is also a candidate for the root cause. 

`webView.RequestContext = new CefSharp.RequestContext();`

**Comment by amaitland** [comment]
> webView.RequestContext = new CefSharp.RequestContext();

This will use an in memory cache. Cookies won't be persisted. 

https://github.com/cefsharp/CefSharp/wiki/General-Usage#request-context-browser-isolation

**Comment by dasgarner** [comment]
Thanks for the link - we will provide a cache path in the next release

```
var requestContextSettings = new RequestContextSettings { CachePath = cachePath };
```

**Comment by amaitland** [comment]
> RequestContextSettings.CachePath must be equal to or a child of  CefSettings.RootCachePath see https://github.com/cefsharp/CefSharp/issues/3111#issuecomment-629713608

You'll also need to set RootCachePath

**Comment by dasgarner** [comment]
Much appreciated - thank you!

**Comment by s1nmorph** [comment]
Hey there @dasgarner  i have been puzzling with this for a few days now as i am fairly new to all this, can you please help me implement the cookie structure in my form?
I do not know how to get cookies to work in my application, as i found your posts on the internet about cookies and cefsharp, but i am missing important steps i think, thank you in advance!

**Comment by dasgarner** [comment]
It's great to see new people getting into C#/cef/programming! The best way to get help is to go ahead and ask your question on stackoverflow: https://stackoverflow.com/. Make sure you read the rules first and understand how to structure your question, giving as much information as possible.

Good luck!
