### ISSUE TITLE
Scheduled Actions

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo-dotnetclient#234]
New event type in schedule XMDS response for scheduled actions.
CMS: xibosignage/xibo#2322

**Comment by Ibamia** [comment]
Bonjour j'ai besoin d'aide pour l'installation de xibo cms.

**Comment by alexharrington** [comment]
> Bonjour j'ai besoin d'aide pour l'installation de xibo cms.

Please post your question on our Community site: https://community.xibo.org.uk

We do not offer support via GitHub

**Comment by Ibamia** [comment]
Hello i have a difficulty of installation Xibo Cms. I easy installation
with xamp and Wamp but the answer print 404 Not Found.and i install Docker
Desktop but the resultat print "An Unexpected error occurred,
Hardware assited virtualization and data execution protrection must be
enable in the bios " also i need that you help me

Le mar. 21 déc. 2021 à 14:31, Alex Harrington ***@***.***> a
écrit :

**Comment by alexharrington** [comment]
This is not the right place to get support. Please post in our Community site: https://community.xibo.org.uk
