### ISSUE TITLE
Data Widgets: DataAgent cache not ready on one widget blocks all widgets

### ISSUE THREAD

**Issue by dasgarner** [xibosignage/xibo-dotnetclient#342]
If you have a widget for which the cache cannot be generated, it blocks any subsequent widgets from downloading their data. If this happens to be the first widget in the download queue, that would mean all widgets.

**Comment by Commifreak** [comment]
Is this related to https://community.xibo.org.uk/t/r403-dataagent-cache-not-ready/32734/31 ?

**Comment by dasgarner** [comment]
Not directly, but it would prevent an error with one widget from effecting them all.

**Comment by Commifreak** [comment]
Seems to affect my issue in positive way. We‘ll see.
