### ISSUE TITLE
IE Browser Issues

### ISSUE THREAD

**Issue by earlgrei** [xibosignage/xibo-dotnetclient#76]
I have had a bunch of issues where we have had to play games due to IE issues and I have hit a show stopper.  We are using a product called Ignition from Inductive Automation.  It 100% does not support IE.  I am going to attempt to roll in CEFSharp myself into the Windows player to get this past this for our purposes.  However it may be something your developers want to look at.  If/When I get it working I would be happy to share code back for your developers perusal.

https://cefsharp.github.io/

**Comment by dasgarner** [comment]
I am not sure if I have any examples which were a particular problem, but from memory we would get crashes after a few days of usage. This was with the standard Xibo widgets, text, weather, twitter and so on.

It may well be that cefsharp itself has moved on and is better at managing memory.

This is how we did it before, if you'd like to compare? https://github.com/xibosignage/xibo-dotnetclient/blob/release/tuttle/Media/CefWebMedia.cs

**Comment by earlgrei** [comment]
Dan,
  I have not had a chance to go extend my deployment further than basic functionality but you *MIGHT* want to revisit CEFSharp.  I have included a memory monitor graph from my monitoring system of the XiboClient.exe  This is using CEFSharp > v70.  I dont recall exactly which version.

![image](https://user-images.githubusercontent.com/1480392/57853150-a2252600-77aa-11e9-8cba-3f8f81088ab4.png)

**Comment by dasgarner** [comment]
We're going to have a look at this: https://github.com/xibosignage/xibo-dotnetclient/issues/86 to see if that is a possible drop in replacement / how it works, etc.

**Comment by dasgarner** [comment]
https://github.com/xibosignage/xibo-dotnetclient/pull/87
