### ISSUE TITLE
Expiry Dates not working if Widget is on its own in Region

### ISSUE THREAD

**Issue by DanielBW1** [xibosignage/xibo-dotnetclient#78]
Player version: V2-200

Issue: Create a Layout that has one Region with one Widget in it. Use the Expiry Dates Tool to add a  Start and End time to the Widget. When the Layout is scheduled on the Player, it will show the widget even if it is before the Start time.

Notes: Adding another Widget to the Region resolves the issue.

**Comment by alexharrington** [comment]
I'm wondering if we can do something better in that scenario then? Could we inject an empty text widget or something rather than show what the user has indicated should not be shown?

**Comment by PGPATRICK** [comment]
I've run into this same issue. Are players have one region to display fullscreen "welcome" and Happy Birthday images, etc., so I'm not sure we can add another region. We need to be able to add an image in the timeline and then have it start and stop on specific dates.
We're on the following:
Xibo Player Version: 2R200
Version OS: Windows 10

**Comment by dasgarner** [comment]
Sorry, I'm not sure I completely understand your use case.

You have a single region layout which contains only 1 widget, which you want to assign a from/to date so that it only shows between two specific dates?

If yes, then you should simply schedule the whole layout using the scheduling tool.

If no, then I am not sure why you don't have another item in the region? (Alex's suggested solution is to show a blank gap, but actually I think you might want the Layout to be skipped?)

**Comment by PGPATRICK** [comment]
Hi Dan,

Perhaps this can illustrate the issue better. This is the timeline for this particular play it run 24x7 and only displays each image full screen.

What we need to do is add a August Birthdays image and use the Expiry date so it starts on Aug. 1. The 2nd FLR – July Birthdays uses Expiry date to stop at the end of July. The stop function is working. If we add the August image today, even with the Expiry start date for Aug. 1, it will display the image.

[cid:image001.png@01D540AD.FD3A6480]

So, we’re not needing a new layout to start, we need a new image in a Timeline to start.

Does that help?

Perry

PERRY PATRICK | Principal Analyst 1 | Enterprise Client Support |  Cox Media Group Technology<http://www.cmgdigital.com/>
 | 223 Perimeter Center Parkway NE | Atlanta, Ga., 30346-1301

**Comment by dasgarner** [comment]
I think I understand - effectively the Layout should be skipped when all of the Widgets in your full screen Region were outside their time window. This is in-line with what the other players do already, so we will try to make that work on Windows.
