### ISSUE TITLE
Player not handling z-index correctly

### ISSUE THREAD

**Issue by schokotets** [xibosignage/xibo-dotnetclient#80]
First of all, the windows player ignores the regions' z-index property.
regions. 
~~Second, it shows the region that's highest in the timeline above, which is exactly opposite the way the cms previews the layout regions (the cms puts the lowest timeline layer above).~~
Edit: That order is handled correctly by the Player. I was confused because of the black background that's behind every area.

**Comment by dasgarner** [comment]
Appreciate this has been a long time - we've handled this in the v2 R252 release, so I will update and close accordingly.
