### ISSUE TITLE
player installation location not set in watchdog config file

### ISSUE THREAD

**Issue by ZoranIT** [xibosignage/xibo-dotnetclient#81]
when the windows player is not installed in the default directory the watchdog config file is not configured correctly to the location.
I have tested it with the white label installer. When replacing the watchdog.exe with the actual one in the repository it works.
The error happens when you start xibowatchdog instead of xibo player.

**Comment by alexharrington** [comment]
Thanks for your report.

You shouldn't directly launch the watchdog. The Player launches it when it starts if no watchdog is running, and will correctly configure the paths based on the install location.
