### ISSUE TITLE
XiboClient.exe *32 Process still shows even after closing

### ISSUE THREAD

**Issue by JaySMa** [xibosignage/xibo-dotnetclient#82]
Hello..
Noticed that even after stopping the Player and the Watchdog, XiboClient.exe *32 still shows up as a running process within Windows Task Manager.

Shouldn't this stop when both are stopped?

Thank you..

**Comment by JaySMa** [comment]
Just did another test and after starting the client (via the Player Options program), killed it and the Watchdog (right-click, exit).

Checked Windows Task manager and it showing XboClientWatchdog.exe *32 is still running.  After a short time, the XboClient.exe *32 process restarts automatically and the player will start displaying slides once agian shortly thereafter.

Seems like the only way to kill this is to kill both the processes.

Thank you..

**Comment by dasgarner** [comment]
This issue tracker is for verified bug reports only please - if you have things you'd like to discuss or ask then the Xibo community is the place to do that.

Many thanks!
